name: CICD

on:
    push:
      branches:
      - 'dev'

jobs:
  build-and-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: generate zip file
        run: zip -r game2048.zip .
      


      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           application_name: 'my-game-app'
           environment_name: 'My-game-app-env'
           version_label: ${{ github.sha }}
           region: eu-west-1
           deployment_package: game2048.zip