name: CICD

on:
    push:
      branches:
      - 'dev'
  
permissions:
    id-token: write  
    contents: read 

jobs:
  build-and-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: generate zip file
        run: zip -r game2048.zip .
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
       
           application_name: 'my-game-app'
           environment_name: 'My-game-app-env'
           aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           version_label: ${{ github.sha }}
           region: eu-west-1
           deployment_package: game2048.zip
        